version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "Tsuyoshi84"
    open-pull-requests-limit: 10
    groups:
      lint-and-format:
        patterns:
          - "*eslint*"
          - "*stylelint*"
          - "*prettier*"
      test:
        patterns:
          - "@playwrite/*"
          - "vitest"
      svelte:
        patterns:
          - "@sveltejs/*"
          - "*svelte*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "github_actions"
    commit-message:
      prefix: "github-actions"
    open-pull-requests-limit: 30