name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.14.4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install package
        run: pnpm install

      # - name: Unit Test
      #   run: pnpm test:unit

      - name: Check
        run: pnpm check

      - name: Lint
        run: pnpm lint:fix

      - name: Lint CSS
        run: pnpm lint-css:fix

      - name: Format
        run: pnpm format

      - name: Install playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Playwright test
        run: pnpm exec playwright test

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5

      - name: Build
        run: pnpm build

  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{ github.actor == 'dependabot[bot]' && github.event_name == 'pull_request' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Wait for checks to pass
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: 'test'
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Merge PR
        if: ${{ steps.wait-for-checks.outputs.conclusion == 'success' }}
        run: gh pr merge --auto --squash ${{ github.event.pull_request.html_url }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
