name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install package
        run: npm install

      # - name: Unit Test
      #   run: npm run test:unit

      # - name: Test
      #   run: npm test

      - name: Check
        run: npm run check

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build
