name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.vscode/**'

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8.x.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install package
        run: pnpm install

      # - name: Unit Test
      #   run: pnpm test:unit

      - name: Install playwright browsers
        run: pnpx playwright install-deps chromium

      - name: Test
        run: pnpm test

      - name: Check
        run: pnpm check

      - name: Lint
        run: pnpm lint

      - name: Format
        run: pnpm format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5

      - name: Build
        run: pnpm build
